name: 'Reset TT By Track Number'

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          curl \
            -XPOST \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${{ github.event.client_payload.slack_token }}" \
            -d '{"channel": "${{ github.event.client_payload.channel_id }}", "text": "ğŸƒ å‰Šé™¤ã—ã¦ã„ã¾ã™"}' \
            https://slack.com/api/chat.postMessage
      - run: cargo run -p ecogreen-slack -- ${{ secrets.CONNECTION_STRING }} ${{ github.event.client_payload.track_number }}
      - run: |
          curl \
            -XPOST \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${{ github.event.client_payload.slack_token }}" \
            -d '{"channel": "${{ github.event.client_payload.channel_id }}", "text": "âœ… å‰Šé™¤ãŒå®Œäº†ã—ã¾ã—ãŸ"}' \
            https://slack.com/api/chat.postMessage
